version: 2.1
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml'  | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: |-
            mvn clean test
            mvn install -Dbuild.number=${CIRCLE_BUILD_NUM} -DskipTests
      - store_test_results:
          path: target/surefire-reports
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |-
            # cp gameoflife-web/target/gameoflife*.war gameoflife-web/target/gameoflife.war
            TAG=0.1.$CIRCLE_BUILD_NUM
            cd gameoflife-web
            docker build -t CircleCI-Public/gameoflife:$TAG .
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'
workflows:
  build-and-test:
    jobs:
      - test-java
